name: Release new version to npm

on:
  push:
    branches:
      - master

env:
  CI: true

jobs:
  release:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout to repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      - name: Build the package
        run: bun run build
      - name: Create and publish version
        uses: changesets/action@v1
        with:
          version: bun run ci:version
          publish: bun run ci:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
