name: Release new configuration version to npm

on:
  push:
    branches:
      - master

env:
  CI: true

jobs:
  release:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      - name: Create and publish version
        uses: changesets/action@v1
        with:
          version: bun ci:version
          publish: bun ci:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
